apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: platform
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdEo=

  SENTRY_DSN: aHR0cHM6Ly82M2Y0YjFmMTA5N2MyMGU3ZGM3NDMwNjdmMzNkZjc2YUBvNDUxMDIwNDYzNjAzNzEyMC5pbmdlc3QuZGUuc2VudHJ5LmlvLzQ1MTAyMDQ3NzgxMTkyNDg=